### ISSUE TITLE
id clashes

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#22]
some schemes and assumptions have the same id, leading to id clashes in the html. The simplest solution may be to prefix ids, so that we're fine as long as ids are unique within a .yml file.

**Comment by GiacomoPope** [comment]
This should have already been addressed in https://github.com/issikebrokenyet/issikebrokenyet.github.io/commit/7bb3776fc96b49598a225fe43409fcaba66baec0

At least this was my fix when I noticed the comment toggle wasn't working.

Indeed, I prefixed the table name in with the element id

**Comment by defeo** [comment]
We still have these (at least):

https://github.com/issikebrokenyet/issikebrokenyet.github.io/blob/7bb3776fc96b49598a225fe43409fcaba66baec0/src/build.py#L77
https://github.com/issikebrokenyet/issikebrokenyet.github.io/blob/7bb3776fc96b49598a225fe43409fcaba66baec0/src/build.py#L118
https://github.com/issikebrokenyet/issikebrokenyet.github.io/blob/7bb3776fc96b49598a225fe43409fcaba66baec0/src/build.py#L178
https://github.com/issikebrokenyet/issikebrokenyet.github.io/blob/7bb3776fc96b49598a225fe43409fcaba66baec0/src/build.py#L125
https://github.com/issikebrokenyet/issikebrokenyet.github.io/blob/7bb3776fc96b49598a225fe43409fcaba66baec0/src/build.py#L186

**Comment by GiacomoPope** [comment]
Oh! Yes, I only addressed the comment ids. I'll apply the same logic and fix these too.

**Comment by GiacomoPope** [comment]
Fixed in commit https://github.com/issikebrokenyet/issikebrokenyet.github.io/commit/a8d2a96676d360be1949e10a4253cd17c92e3bf9
